### ISSUE TITLE
geosproket demo tiles not working

### ISSUE THREAD

**Issue by harry-wood** [wboykinm/tile-compare#1]
All of the layers still work apart form the geosproket demo.

Looks like mapbox hosted layer defined here: https://github.com/wboykinm/tile-compare/blob/master/index.html#L171 not sure why it's not working

**Comment by wboykinm** [comment]
@harry-wood Wow, I haven't even looked at this sucker in years. I believe I deleted that tileset to save space in my Mapbox account.

**Comment by wboykinm** [comment]
https://github.com/wboykinm/tile-compare/pull/3/files

**Comment by harry-wood** [comment]
Ah you found the old tiles hey? Nice one.

I remember this site seemed to get a bit of attention back when you first made it. I found it again recently because there's a link to it somewhere on the osm wiki. ...bug I can't find where now.

**Comment by wboykinm** [comment]
@harry-wood It was so long ago I actually used the google maps api for it 😬 . Your reminder had me thinking it'd be fun to do again, but good lord; how do you even choose points of comparison anymore? Favorite dark basemap? Favorite high-contrast basemap? Favorite ancient-manuscript-style basemap?
